### PR TITLE
Switch to using terminus instead of pantheon-cli

### PR DESCRIPTION
**Pull request by davidsparks**

### CODE REVIEW

**Comment by andyg5000** [comment]
+1 as the `require katzgrau/klogger:dev-master` causes a build failure

**Comment by greg-1-anderson** [comment]
Not sure how well this repo is working at the moment, as I am no longer actively maintaining it.  I merged this without testing as the state prior to this PR is clearly worse. Sorry I didn't see this back when it was submitted.

**Comment by davidsparks** [comment]
No worries Greg - I’m sure most people are just using this as a code example to build from rather than expecting it to work 100% out of the box. You’ve done a great job helping people like me get to grips with CI - thank you!

**Comment by greg-1-anderson** [comment]
The example I'm maintaining right now is https://github.com/pantheon-systems/example-drops-8-composer. The Drupal 7 example is still on my to-do list, though.

**Pull request merged**
